package com.google.blockly.android.webview.utility;

public interface Codes {
    int STT_DO_COMMAND_CODE = 10;
    int STT_GET_NAME = 12;
    int STT_GET_CITY_NAME = 13;
    int ASK_NAME_UTTERANCE_ID = 14;
    int ASK_CITY_UTTERANCE_ID = 15;
    int IDLE_UTTERANCE_ID = 16;
    int INSTALL_TTS_DATA_CODE = 17;
    int REQUEST_AUDIO_PERMISSIONS = 18;
    int BLUETOOTH_ACTION_REQUEST_ENABLE = 19;
    int BLUETOOTH_ACTION_REQUEST_DISCOVERABLE = 20;
    int SYNTHESIZE_To_FILE_UTTERANCE_ID = 21;
    int FILE_CHOOSER_RESULT_CODE = 22;
    int BLUETOOTH_DISCOVERABLE_DURATION = 120;
    int MUSIC_PLAYER_NOTIFICATION_ID = 2;

    int MY_PERMISSIONS_REQUEST_RECORD_AUDIO = 10;
    int MY_PERMISSIONS_REQUEST_WRITE_STORAGE_FILE = 11;
    int MY_PERMISSIONS_REQUEST_READ_STORAGE_FILE = 12;
    int MY_PERMISSIONS_REQUEST_READ_CONTACTS = 13;
    int MY_PERMISSIONS_REQUEST_GET_ACCOUNTS = 14;
    int MY_PERMISSIONS_REQUEST_INTERNET = 15;
    int MY_PERMISSIONS_REQUEST_BLUETOOTH = 16;
    int MY_PERMISSIONS_REQUEST_BLUETOOTH_ADMIN = 17;
}
